export const FIELD_DEFINITIONS = [
  ['scope', 'Was soll geliefert werden?'],
  ['products', 'Produkte / Artikel'],
  ['quantities', 'Mengen'],
  ['sizes', 'Größen'],
  ['materials', 'Materialien'],
  ['colors', 'Farben'],
  ['finishing', 'Veredelungen / Logos / Druck / Stick'],
  ['quality', 'Qualitätsanforderungen'],
  ['standards', 'Normen / Zertifizierungen'],
  ['samples', 'Muster / Bemusterung'],
  ['delivery_locations', 'Lieferorte'],
  ['delivery_deadlines', 'Lieferfristen'],
  ['contract_duration', 'Vertragslaufzeit'],
  ['lots', 'Lose'],
  ['options', 'Optionen / Verlängerungen'],
  ['minimum_requirements', 'Mindestanforderungen'],
  ['eligibility_evidence', 'Eignungsnachweise'],
  ['references', 'Referenzen'],
  ['turnover', 'Umsatzanforderungen'],
  ['insurance', 'Versicherungen'],
  ['exclusion_criteria', 'Ausschlusskriterien'],
  ['award_criteria', 'Zuschlagskriterien'],
  ['price_weighting', 'Preisgewichtung'],
  ['payment_terms', 'Zahlungsbedingungen'],
  ['contract_penalties', 'Vertragsstrafen'],
  ['warranty', 'Gewährleistung'],
  ['submission_deadline', 'Angebotsfrist'],
  ['questions_deadline', 'Fragenfrist'],
  ['required_forms', 'Einzureichende Formulare'],
  ['signatures', 'Unterschriften'],
  ['variants', 'Nebenangebote'],
  ['consortia', 'Bietergemeinschaften'],
  ['risks', 'Besondere Risiken'],
  ['contradictions', 'Widersprüchliche / unklare Angaben']
] as const;

export type FieldKey = (typeof FIELD_DEFINITIONS)[number][0];
export const FIELD_KEYS = FIELD_DEFINITIONS.map(([key]) => key);
